import { Injectable } from '@angular/core';

import {
  BackofficePlayersRepository,
  type BackofficePlayerUpdate,
} from '@features/backoffice/application/ports/backoffice-players.repository';
import type { BackofficePlayer } from '@features/backoffice/domain/entities/backoffice-player';

let MOCK_PLAYERS: BackofficePlayer[] = [
  // ── Kings Of Favar ────────────────────────────────────────────────────────
  {
    id: 'kings-of-favar-player-1',
    firstName: 'Vicent',
    lastName: 'Ciscar',
    email: 'vicent@kingspadel.com',
    profileImage: '/stock_players/player-01.svg',
    isPresident: true,
    teamId: 'kings-of-favar',
    value: 85,
    wonGames: 4,
    lostGames: 1,
    preferredPosition: 'both',
    description: 'Capitán y fundador del equipo.',
  },
  {
    id: 'kings-of-favar-player-2',
    firstName: 'Enric',
    lastName: 'Bixquert',
    email: 'enric@kingspadel.com',
    profileImage: '/stock_players/player-02.svg',
    isPresident: false,
    teamId: 'kings-of-favar',
    value: 78,
    wonGames: 3,
    lostGames: 2,
    preferredPosition: 'both',
    description: 'Jugador versátil del equipo.',
  },
  {
    id: 'kings-of-favar-player-3',
    firstName: 'Alex',
    lastName: 'Pla',
    email: 'alex@kingspadel.com',
    profileImage: '/stock_players/player-03.svg',
    isPresident: false,
    teamId: 'kings-of-favar',
    value: 72,
    wonGames: 2,
    lostGames: 2,
    preferredPosition: 'both',
    description: 'Jugador polivalente.',
  },
  {
    id: 'kings-of-favar-player-4',
    firstName: 'Andreu',
    lastName: 'Simo',
    email: 'andreu@kingspadel.com',
    profileImage: '/stock_players/player-04.svg',
    isPresident: false,
    teamId: 'kings-of-favar',
    value: 70,
    wonGames: 2,
    lostGames: 3,
    preferredPosition: 'both',
    description: 'Jugador constante y seguro.',
  },
  // ── Magic City ────────────────────────────────────────────────────────────
  {
    id: 'magic-city-player-1',
    firstName: 'Adri',
    lastName: 'Alvarez',
    email: 'adri@kingspadel.com',
    profileImage: '/stock_players/player-03.svg',
    isPresident: true,
    teamId: 'magic-city',
    value: 80,
    wonGames: 2,
    lostGames: 3,
    preferredPosition: 'left',
    description: 'Presidente y motor del equipo.',
  },
  {
    id: 'magic-city-player-2',
    firstName: 'Josep',
    lastName: 'Castello',
    email: 'josep@kingspadel.com',
    profileImage: '/stock_players/player-04.svg',
    isPresident: false,
    teamId: 'magic-city',
    value: 74,
    wonGames: 1,
    lostGames: 3,
    preferredPosition: 'right',
    description: 'Especialista en drive.',
  },
  // ── Titanics ──────────────────────────────────────────────────────────────
  {
    id: 'titanics-player-1',
    firstName: 'Adrian',
    lastName: 'Asuncion',
    email: 'adrian@kingspadel.com',
    profileImage: '/stock_players/player-04.svg',
    isPresident: true,
    teamId: 'titanics',
    value: 90,
    wonGames: 5,
    lostGames: 0,
    preferredPosition: 'left',
    description: 'Presidente y mejor jugador de la liga.',
  },
  {
    id: 'titanics-player-2',
    firstName: 'Brigante',
    lastName: '',
    email: 'brigante@kingspadel.com',
    profileImage: '/stock_players/player-05.svg',
    isPresident: false,
    teamId: 'titanics',
    value: 82,
    wonGames: 4,
    lostGames: 1,
    preferredPosition: 'right',
    description: 'Potencia en el lado derecho.',
  },
  {
    id: 'titanics-player-3',
    firstName: 'Carles',
    lastName: 'Montilla',
    email: 'carles@kingspadel.com',
    profileImage: '/stock_players/player-01.svg',
    isPresident: false,
    teamId: 'titanics',
    value: 75,
    wonGames: 3,
    lostGames: 2,
    preferredPosition: 'left',
    description: 'Sólido en defensa.',
  },
  {
    id: 'titanics-player-4',
    firstName: 'Dani',
    lastName: 'Sanchez',
    email: 'dani.s@kingspadel.com',
    profileImage: '/stock_players/player-01.svg',
    isPresident: false,
    teamId: 'titanics',
    value: 71,
    wonGames: 3,
    lostGames: 2,
    preferredPosition: 'both',
    description: 'Juega en cualquier posición.',
  },
  // ── Barbaridad Team ───────────────────────────────────────────────────────
  {
    id: 'barbaridad-player-1',
    firstName: 'Samu',
    lastName: '',
    email: 'samu@kingspadel.com',
    profileImage: '/stock_players/player-05.svg',
    isPresident: true,
    teamId: 'barbaridad',
    value: 68,
    wonGames: 0,
    lostGames: 5,
    preferredPosition: 'left',
    description: 'Presidente y corazón del equipo.',
  },
  {
    id: 'barbaridad-player-2',
    firstName: 'Miguel',
    lastName: 'Esteve',
    email: 'miguel@kingspadel.com',
    profileImage: '/stock_players/player-06.svg',
    isPresident: false,
    teamId: 'barbaridad',
    value: 65,
    wonGames: 0,
    lostGames: 4,
    preferredPosition: 'both',
    description: 'Jugador en desarrollo.',
  },
  {
    id: 'barbaridad-player-3',
    firstName: 'Raul',
    lastName: 'Bataller',
    email: 'raul@kingspadel.com',
    profileImage: '/stock_players/player-01.svg',
    isPresident: false,
    teamId: 'barbaridad',
    value: 66,
    wonGames: 0,
    lostGames: 4,
    preferredPosition: 'both',
    description: 'Luchador incansable.',
  },
  // ── Thormentadores ────────────────────────────────────────────────────────
  {
    id: 'thormentadores-player-1',
    firstName: 'Borja',
    lastName: 'Vercher',
    email: 'borja@kingspadel.com',
    profileImage: '/stock_players/player-06.svg',
    isPresident: true,
    teamId: 'thormentadores',
    value: 86,
    wonGames: 4,
    lostGames: 1,
    preferredPosition: 'both',
    description: 'Presidente y referente del equipo.',
  },
  {
    id: 'thormentadores-player-2',
    firstName: 'Ruben',
    lastName: 'Marzal',
    email: 'ruben@kingspadel.com',
    profileImage: '/stock_players/player-01.svg',
    isPresident: false,
    teamId: 'thormentadores',
    value: 79,
    wonGames: 3,
    lostGames: 2,
    preferredPosition: 'right',
    description: 'Especialista en drive.',
  },
  {
    id: 'thormentadores-player-3',
    firstName: 'Tomas',
    lastName: '',
    email: 'tomas@kingspadel.com',
    profileImage: '/stock_players/player-02.svg',
    isPresident: false,
    teamId: 'thormentadores',
    value: 73,
    wonGames: 3,
    lostGames: 2,
    preferredPosition: 'left',
    description: 'Defensivo y consistente.',
  },
  {
    id: 'thormentadores-player-4',
    firstName: 'Tono',
    lastName: '',
    email: 'tono@kingspadel.com',
    profileImage: '/stock_players/player-03.svg',
    isPresident: false,
    teamId: 'thormentadores',
    value: 70,
    wonGames: 2,
    lostGames: 2,
    preferredPosition: 'both',
    description: 'Jugador versátil.',
  },
  // ── Sin equipo ────────────────────────────────────────────────────────────
  {
    id: 'sin-equipo-player-1',
    firstName: 'Artur',
    lastName: 'Peris',
    email: 'artur@kingspadel.com',
    profileImage: '/stock_players/player-02.svg',
    isPresident: false,
    value: 60,
    wonGames: 0,
    lostGames: 0,
    preferredPosition: 'both',
    description: 'Jugador libre en búsqueda de equipo.',
  },
  {
    id: 'sin-equipo-player-2',
    firstName: 'Damian',
    lastName: 'Crespo',
    email: 'damian@kingspadel.com',
    profileImage: '/stock_players/player-03.svg',
    isPresident: false,
    value: 58,
    wonGames: 0,
    lostGames: 0,
    preferredPosition: 'both',
    description: 'Jugador libre en búsqueda de equipo.',
  },
  {
    id: 'sin-equipo-player-3',
    firstName: 'Joan',
    lastName: 'Meló',
    email: 'joan@kingspadel.com',
    profileImage: '/stock_players/player-04.svg',
    isPresident: false,
    value: 62,
    wonGames: 0,
    lostGames: 0,
    preferredPosition: 'right',
    description: 'Jugador libre en búsqueda de equipo.',
  },
  {
    id: 'sin-equipo-player-4',
    firstName: 'Javi',
    lastName: 'Millet',
    email: 'javi@kingspadel.com',
    profileImage: '/stock_players/player-05.svg',
    isPresident: false,
    value: 61,
    wonGames: 0,
    lostGames: 0,
    preferredPosition: 'both',
    description: 'Jugador libre en búsqueda de equipo.',
  },
];

@Injectable()
export class InMemoryBackofficePlayersRepository extends BackofficePlayersRepository {
  override loadAll(): Promise<readonly BackofficePlayer[]> {
    return Promise.resolve(MOCK_PLAYERS);
  }

  override update(id: string, input: BackofficePlayerUpdate): Promise<void> {
    MOCK_PLAYERS = MOCK_PLAYERS.map((player) =>
      player.id === id
        ? {
            ...player,
            ...(input.alias !== undefined ? { alias: input.alias } : {}),
            ...(input.firstName !== undefined ? { firstName: input.firstName } : {}),
            ...(input.instagramUrl !== undefined ? { instagramUrl: input.instagramUrl } : {}),
            ...(input.lastName !== undefined ? { lastName: input.lastName } : {}),
            ...(input.preferredPosition !== undefined
              ? { preferredPosition: input.preferredPosition }
              : {}),
            ...(input.profileImage !== undefined ? { profileImage: input.profileImage } : {}),
          }
        : player,
    );

    return Promise.resolve();
  }
}
